name: Compose

on: push
     branches: [ master ]

jobs:
  build:
    name: Push Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant Permission to Execute
        run: chmod +x gradlew

      - name: "detekt"
        uses: natiginfo/action-detekt-all@1.15.0-RC1

      - name: Run Lint
        run: ./gradlew lint

